image: python:3.11-bookworm

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; python -m pip --version  # For debugging
  - apt-get update
  - apt-get install -y libgdal-dev g++ binutils libproj-dev gdal-bin --no-install-recommends
  - python -m pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  stage: deploy
  environment: production
  script:
      - python -m pip install sphinx sphinx_rtd_theme
      - python -m pip install .
      - sphinx-apidoc -f -e -M -o doc/source .
      - sphinx-build -d doc/build doc/source public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH