image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version ; pip --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  stage: deploy
  environment: production
  script:
      - pip install sphinx sphinx_rtd_theme
      # - pip install -r requirements.txt
      - sphinx-apidoc -f -e -M -o doc/source u4py
      - sphinx-build -d doc/build doc/source public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH