[metadata]
name = u4py
version = 0.0.2dev

[options]
packages=u4py
install_requires=
    contextily
    dbfread
    ete3
    geopandas
    h5py
    ipython
    matplotlib
    numba
    numba_progress
    numpy
    osmnx
    pandas
    pycwt
    pyproj
    rasterio
    scipy
    setuptools
    Shapely
    scikit-image
    tensorflow
    tqdm
    uncertainties
