[metadata]
name = u4py
version = 0.0.4dev

[options]
packages=u4py, u4py.addons, u4py.analysis, u4py.plotting, u4py.utils
install_requires=
    bmi_arcgis_restapi
    contextily
    dbfread
    ete3
    ffmpeg_python
    Fiona
    geopandas
    geopy
    h5py
    ipython
    matplotlib
    numba
    numba_progress
    numpy
    openpyxl
    osmnx
    pandas
    pycwt
    pyproj
    rasterio
    scipy
    setuptools
    Shapely
    skimage
    tensorflow
    tensorflow_intel
    tqdm
    uncertainties
    utm
