[metadata]
name = u4py
version = 0.0.9

[options]
packages=u4py, u4py.addons, u4py.analysis, u4py.plotting, u4py.utils, u4py.io
install_requires=
    bmi_arcgis_restapi
    contextily
    ffmpeg_python
    fiona
    GDAL == 3.6.2;platform_system=="Linux"
    GDAL;platform_system=="Windows"
    geopandas
    geopy
    ipython
    mahotas
    matplotlib
    numpy
    openpyxl
    osmnx
    packaging
    pandas
    pathvalidate
    pycwt
    pyproj
    rasterio
    scipy
    setuptools
    Shapely
    scikit-image
    tqdm
    uncertainties
    utm
