"""
Generates a video from the GeoTiffs generated by `plot_psi_as_tiffs.py`.

This script uses all tiff files in `output_path` folder to generate the plots.
To zoom into specific regions, it supports the use of a shape file with
polygon shapes. Currently this is hardcoded to be `FFM_Regions.shp` but in
future might shift to all polygons in a selected file.

Parameters that can be changed are:

 - `overwrite` -> Overwrites existing Tiffs
 - `shp_name` -> Shapefile (has to contain `Name` column)
 - `region_name` -> The `Name` to select.
 - `fps` -> Frames per second of final video
 - `vm` -> Colorbar min/max value

"""

import os

import contextily
import ffmpeg
import geopandas as gp
import matplotlib.pyplot as plt
from tqdm import tqdm

import u4py.plotting.axes as u4ax
import u4py.plotting.formatting as u4plotfmt
import u4py.utils.projects as u4proj


def main():
    # ------ Parameters -------------------------------------------------------
    overwrite = True  # Overwrites existing Tiffs
    shp_name = "FFM_Regions.shp"  # Shapefile (has to contain `Name` column)
    region_name = "Crumstadt"  # The `Name` to select.
    fps = 10  # Frames per second of final video
    vm = 25  # Colorbar min/max value

    # ------ Script -----------------------------------------------------------
    project = u4proj.get_project(
        required=["output_path", "places_path"],
        # interactive=False,
    )

    # Setting up Paths
    out_folder = os.path.join(project["paths"]["output_path"], region_name)
    os.makedirs(out_folder, exist_ok=True)
    video_path = os.path.join(out_folder, f"{region_name}.mp4")
    regions_path = os.path.join(project["paths"]["places_path"], shp_name)

    # Loading Regions for extraction
    regions_gdf = gp.read_file(regions_path)
    bounds = regions_gdf[regions_gdf.Name == region_name].bounds

    # Generating JPGs
    if overwrite:
        file_list = [
            fname
            for fname in os.listdir(project["paths"]["output_path"])
            if fname.endswith(".tif")
        ]
        fig, ax = plt.subplots(figsize=(12, 10))  # Common figure
        for ii, fname in tqdm(
            enumerate(file_list),
            total=len(file_list),
            desc="Creating JPGs",
        ):
            if ii:  # Colorbar is plot for first run and stays on plot later
                colorbar = False
            else:
                colorbar = {
                    "shrink": 0.7,
                    "extend": "both",
                    "label": "Vertical Displacement (mm)",
                }

            # Add the GeoTiff to plot
            _, crs = u4ax.add_tile(
                os.path.join(project["paths"]["output_path"], fname),
                ax=ax,
                cmap="RdBu",
                vm=vm,
                imsize=0,
                colorbar=colorbar,
                zorder=2,
            )

            # Using shapes as boundary
            ax.set_xlim(float(bounds.minx.iloc[0]), float(bounds.maxx.iloc[0]))
            ax.set_ylim(float(bounds.miny.iloc[0]), float(bounds.maxy.iloc[0]))

            # Add basemap, format and save
            contextily.add_basemap(
                ax=ax,
                source=contextily.providers.OpenStreetMap.Mapnik,
                crs=crs,
                zorder=1,
            )
            ax.set_title(fname.replace(".tif", ""))
            u4plotfmt.map_style(ax=ax, divisor=2000, crs=crs)
            fig.savefig(os.path.join(out_folder, f"{ii:03}.jpg"))
            ax.clear()

    # Making Video (overwrites existing video.)
    if os.path.exists(video_path):
        os.remove(video_path)
    (
        ffmpeg.input(
            os.path.join(out_folder, "%03d.jpg"),
            framerate=fps,
        )
        .output(video_path)
        .run()
    )


if __name__ == "__main__":
    main()
